version: '3.8'
services:
  type:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./app:/app

  npm:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - ./app:/app
      - /app/node_modules
