version: '3.8'
services:
  type:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - ./app/node_modules:/app/node_modules
      - ./app:/app

  npm:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - ./app/node_modules:/app/node_modules
      - ./app:/app

  # RUN Json-Server
  json:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - '3030:3030'
    command: npm run json
    volumes:
      - ./app/node_modules:/app/node_modules
      - ./app:/app

  # create-react-app with typescript
  create-react-app:
    image: node:16
    working_dir: /app
    command: npx create-react-app my-app --template typescript
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
